version: 2
jobs:
  build:
    branches:
      only:
        - jinja
    docker:
      - image: continuumio/miniconda3:4.7.12
    steps:
      - checkout
      - run:
          name: Configure conda
          command: |
            conda config --set always_yes yes
            conda config --set quiet yes
            conda config --set changeps1 no
            conda config --set auto_update_conda no
            conda config --add channels defaults
            conda config --add channels conda-forge
      - run:
          name: Installation
          command: |
            conda install git make staticjinja
            conda list
      - run:
          name: Build site
          command: make build
      - add_ssh_keys:
          fingerprints:
            - "3e:63:7c:f7:de:49:df:90:36:91:9b:83:7c:58:37:45"
      - run:
          name: Deploy site to GitHub Pages
          command: |
            if [[ "${CI}" = "true" && "${CIRCLECI}" = "true" && "${CIRCLE_USERNAME}" = "jdblischak" && -z "${CIRCLE_PULL_REQUEST}" && -d _site/ ]]
            then
              echo "Deploying to GitHub Pages"
              git config --global user.email "jdblischak@gmail.com"
              git config --global user.name "CircleCI Job"
              git checkout gh-pages
              cp -R _site/* .
              git add *html assets/ img/
              git commit -m "Site built from ${CIRCLE_SHA1} on `date --rfc-3339=s` [skip ci]"
              git push origin gh-pages
            else
              echo "The site was not deployed"
            fi
      - store_artifacts:
          path: _site/
