version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3:4.7.12
    steps:
      - checkout
      - run:
          name: Configure conda
          command: |
            conda config --set always_yes yes
            conda config --set quiet yes
            conda config --set changeps1 no
            conda config --set auto_update_conda no
            conda config --add channels defaults
            conda config --add channels conda-forge
      - run:
          name: Installation
          command: |
            conda install git make staticjinja
            conda list
      - run:
          name: Build site
          command: make build
      - store_artifacts:
          path: _site/
