version: 2
jobs:
  build:
    branches:
      only:
        - main
    docker:
      - image: condaforge/mambaforge:4.10.3-1
    steps:
      - checkout
      - run:
          name: Configure conda
          command: |
            conda config --set always_yes yes
            conda config --set quiet yes
            conda config --set changeps1 no
            conda config --set auto_update_conda no
      - run:
          name: Installation
          command: |
            mamba install git make staticjinja
            conda list
      - run:
          name: Build site
          command: make build
      - add_ssh_keys:
          fingerprints:
            - "bc:08:16:e4:f1:e1:df:f3:5e:ab:0c:bc:9a:c9:1c:91"
      - run:
          name: Deploy site to GitHub Pages
          command: |
            if [[ "${CI}" = "true" && "${CIRCLECI}" = "true" && "${CIRCLE_USERNAME}" = "jdblischak" && -z "${CIRCLE_PULL_REQUEST}" && -d _site/ ]]
            then
              echo "Deploying to GitHub Pages"
              git config --global user.email "jdblischak@gmail.com"
              git config --global user.name "CircleCI Job"
              git checkout gh-pages
              cp -R _site/* .
              git add *html assets/ img/
              git commit --allow-empty -m "Site built from ${CIRCLE_SHA1} on `date --rfc-3339=s` [skip ci]"
              git push origin gh-pages
            else
              echo "The site was not deployed"
            fi
      - store_artifacts:
          path: _site/
